name: Main report

on:
  workflow_dispatch:
  schedule:
    - cron: "35 16 * * *"
    - cron: "25 4 * * *"
    - cron: "5 10 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'

      - uses: actions/checkout@v2

      - name: Setup helium
        shell: pwsh
        run: |
          pip3 install helium

      - name: Auth
        shell: pwsh
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python auth.py

      - name: Daily report.
        if: github.event.schedule == '35 16 * * *'
        env:
          DAILY_REPORT_FORM: ${{ secrets.DAILY_REPORT_FORM }}
        shell: pwsh
        run: |
          ./daily_report.ps1

      - name: Regular check report.
        env:
          IS_AT_SCHOOL: ${{ secrets.IS_AT_SCHOOL }}
        shell: pwsh
        run: |
          ./regular_check.ps1
