name: Manually Regular report

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'

      - uses: actions/checkout@v2

      - name: Setup helium
        shell: pwsh
        run: |
          pip3 install helium

      - name: Auth
        shell: pwsh
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python auth.py

      - name: Regular check report.
        env:
          IS_AT_SCHOOL: ${{ secrets.IS_AT_SCHOOL }}
        shell: pwsh
        run: |
          ./regular_check.ps1
